### ISSUE TITLE
genes not present in gGnome.js instance

### ISSUE THREAD

**Issue by zlskidmore** [mskilab/gGnome.js#18]
Hi,

I'm unable to view any gene tracks, it looks like this functionality is not present in the demos on the README as well. Is the functionality operational?

Thanks!

**Comment by ShaiberAlon** [comment]
Hi @zlskidmore ,

I am not sure I understand the issue.

Here is one of the screenshots from the README:
![image](https://user-images.githubusercontent.com/17661044/146600540-721b43d0-e485-4122-9f94-242c7707c564.png)


On the top right you can see the "optional tracks". And there you can enable the "genes" track. After a short delay the gene track should show up (in the screenshot it is enabled and you see it).

Also, you say "gene tracks", but there is just one track for genes.

One more thing. Are you using hg38 or hg19?

**Comment by zlskidmore** [comment]
Hi @ShaiberAlon 

Here is what I see

<img width="1787" alt="Screen Shot 2021-12-17 at 3 14 54 PM" src="https://user-images.githubusercontent.com/6145692/146608886-997607aa-f24f-41cf-a1b8-376d53c339fe.png">

I am using hg38, here is a head of public/genes.json

```{"genes": [
	{"iid": 427072, "chromosome": "chr19", "startPoint": 58345178, "endPoint": 58353492, "y": 0, "title": "A1BG", "group_id": "5118", "type": "gene", "strand": "-", "weight": 1},
	{"iid": 427073, "chromosome": "chr19", "startPoint": 58353404, "endPoint": 58353437, "y": 0, "title": "A1BG", "group_id": "5118", "type": "CDS", "strand": "-", "weight": 1},
	{"iid": 427074, "chromosome": "chr19", "startPoint": 58353292, "endPoint": 58353327, "y": 0, "title": "A1BG", "group_id": "5118", "type": "CDS", "strand": "-", "weight": 1},
	{"iid": 427075, "chromosome": "chr19", "startPoint": 58352928, "endPoint": 58353197, "y": 0, "title": "A1BG", "group_id": "5118", "type": "CDS", "strand": "-", "weight": 1},
	{"iid": 427076, "chromosome": "chr19", "startPoint": 58352283, "endPoint": 58352555, "y": 0, "title": "A1BG", "group_id": "5118", "type": "CDS", "strand": "-", "weight": 1},
```

**Comment by zlskidmore** [comment]
I didn't see the gene track display genes on the demo here either:
http://mskilab.com/gGraph/index.html?file=DO234435.json&location=1:0-249250619&view=

I have checked and everything seems to match chr-wise, I did look at the code base but was unable to track down the issue, I'm not sure if it's a bug, or an issue with my data.

**Comment by ShaiberAlon** [comment]
Can you please also share the contents of the file

public/metadata.json

**Comment by zlskidmore** [comment]
```
{"metadata": [
		{"chromosome": "chr1", "startPoint": 1, "endPoint": 248956422, "color":  "#1f77b4"},
		{"chromosome": "chr2", "startPoint": 1, "endPoint": 242193529, "color":  "#ff7f0e"},
		{"chromosome": "chr3", "startPoint": 1, "endPoint": 198295559, "color":  "#2ca02c"},
		{"chromosome": "chr4", "startPoint": 1, "endPoint": 190214555, "color":  "#d62728"},
		{"chromosome": "chr5", "startPoint": 1, "endPoint": 181538259, "color":  "#9467bd"},
		{"chromosome": "chr6", "startPoint": 1, "endPoint": 170805979, "color":  "#8c564b"},
		{"chromosome": "chr7", "startPoint": 1, "endPoint": 159345973, "color":  "#e377c2"},
		{"chromosome": "chr8", "startPoint": 1, "endPoint": 145138636, "color":  "#7f7f7f"},
		{"chromosome": "chr9", "startPoint": 1, "endPoint": 138394717, "color":  "#bcbd22"},
		{"chromosome": "chr10", "startPoint": 1, "endPoint": 133797422, "color": "#17becf"},
		{"chromosome": "chr11", "startPoint": 1, "endPoint": 135086622, "color": "#393b79"},
		{"chromosome": "chr12", "startPoint": 1, "endPoint": 133275309, "color": "#5254a3"},
		{"chromosome": "chr13", "startPoint": 1, "endPoint": 114364328, "color": "#6b6ecf"},
		{"chromosome": "chr14", "startPoint": 1, "endPoint": 107043718, "color": "#9c9ede"},
		{"chromosome": "chr15", "startPoint": 1, "endPoint": 101991189, "color": "#637939"},
		{"chromosome": "chr16", "startPoint": 1, "endPoint": 90338345, "color":  "#8ca252"},
		{"chromosome": "chr17", "startPoint": 1, "endPoint": 83257441, "color":  "#b5cf6b"},
		{"chromosome": "chr18", "startPoint": 1, "endPoint": 80373285, "color":  "#cedb9c"},
		{"chromosome": "chr19", "startPoint": 1, "endPoint": 58617616, "color":  "#8c6d31"},
		{"chromosome": "chr20", "startPoint": 1, "endPoint": 64444167, "color":  "#bd9e39"},
		{"chromosome": "chr21", "startPoint": 1, "endPoint": 46709983, "color":  "#e7ba52"},
		{"chromosome": "chr22", "startPoint": 1, "endPoint": 50818468, "color":  "#e7cb94"},
		{"chromosome": "chrX", "startPoint": 1, "endPoint": 156040895, "color":  "#843c39"},
		{"chromosome": "chrY", "startPoint": 1, "endPoint": 57227415, "color":   "#ad494a"}
  ],
"sequences": {"T": "#E6E431", "A": "#5157FB", "G": "#1DBE21", "C": "#DE0A17", "backbone": "#AD26FA"},
"coveragePointsThreshold":  30000,
"scatterPlot": {"title": "Coverage"},
"barPlot":  {"title":  "RPKM"},
"intervalsPanelHeightRatio": 0.6
}
```

**Comment by ShaiberAlon** [comment]
Hi @zlskidmore , Thanks for sharing this and sorry for my delayed response.

So as far as I can see from what you shared it seems your reference files are properly set and hence I am still not sure why you are getting this issue. Are you using Chrome? If so, then could you please follow these steps to help us troubleshoot: 

1. When you have gGnome.js opened in your browser use the mouse right-click and choose "inspect"
2. one the inspection window shows up then choose the "console" tab.
3. Take a screenshot of whatever you see in the console tab and paste here.

Thank you and sorry for these issues.

**Comment by zlskidmore** [comment]
oh interesting,

I was on firefox, the genes do show up on chrome.

thanks @ShaiberAlon !

**Comment by ShaiberAlon** [comment]
Oh wow. Good to know. We have almost exclusively tested the application on Chrome. As a conclusion from your experience I added a note to the README file:

https://github.com/mskilab/gGnome.js/commit/144707d0cb3f411018a6ac40b9807f204e520528

Thank you for your troubleshooting efforts!
